// lib/ui/raahi/benethe_stack.dart
import 'package:flutter/material.dart';

Widget buildBenetheCard(String cardSlug, String backgroundUrl) {
  return Stack(
    alignment: Alignment.topCenter,
    children: [
      // 1. The Imagery Background (Generated by Gemini - Midnight Heritage Aesthetic)
      Image.network(
        backgroundUrl, 
        fit: BoxFit.cover,
        width: double.infinity,
        height: double.infinity,
      ),

      // 2. The Typography Overlay (Renders perfectly over the Safe Zone)
      Positioned(
        top: 45, // Aligned for border-top padding bleeding space
        child: Column(
          children: [
            // The Latin Transliteration (e.g., "(Thari)")
            Text(
              getLatinName(cardSlug),
              style: TextStyle(
                color: Colors.white70,
                fontStyle: FontStyle.italic,
                fontSize: 14,
                letterSpacing: 1.2,
              ),
            ),
            const SizedBox(height: 10),
            // The 100% Accurate Noto Thaana (e.g., "ތަރި")
            // Locked to Gold (#F4B400) as per Visual Framework
            Text(
              getThaanaName(cardSlug),
              style: TextStyle(
                color: Color(0xFFF4B400),
                fontFamily: 'NotoThaana',
                fontWeight: FontWeight.w900,
                fontSize: 36,
                shadows: [
                  Shadow(
                    blurRadius: 10.0,
                    color: Colors.black.withOpacity(0.5),
                    offset: Offset(0, 2),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    ],
  );
}

// Placeholder functions for slug-to-name mapping
String getLatinName(String slug) {
  final map = {
    'fool': '(The Fool)',
    'magician': '(The Magician)',
    'high_priestess': '(The High Priestess)',
    'empress': '(The Empress)',
    'emperor': '(The Emperor)',
    'hierophant': '(The Hierophant)',
    'lovers': '(The Lovers)',
    'chariot': '(The Chariot)',
    'strength': '(Strength)',
    'hermit': '(The Hermit)',
    'wheel_of_fortune': '(Wheel of Fortune)',
    'justice': '(Justice)',
    'hanged_man': '(The Hanged Man)',
    'death': '(Death)',
    'temperance': '(Temperance)',
    'devil': '(The Devil)',
    'tower': '(The Tower)',
    'star': '(The Star)',
    'moon': '(The Moon)',
    'sun': '(The Sun)',
    'judgement': '(Judgement)',
    'world': '(The World)',
  };
  return map[slug.toLowerCase()] ?? '';
}

String getThaanaName(String slug) {
  final map = {
    'fool': 'ސޭކުބެ',
    'magician': 'ޖާދޫގަރު',
    'high_priestess': 'އިސްވެރިޔާ',
    'empress': 'ރާނީ',
    'emperor': 'ރަސްގެފާނު',
    'hierophant': 'އެދުރުބެ',
    'lovers': 'ލޯބިވެރިން',
    'chariot': 'ގާޑިޔާ',
    'strength': 'ބާރު',
    'hermit': 'އެކަހެރިޔާ',
    'wheel_of_fortune': 'ތަދުބީރު',
    'justice': 'އިންސާފު',
    'hanged_man': 'މަރުދަން',
    'death': 'މަރު',
    'temperance': 'ކެތްތެރި',
    'devil': 'އިބިލީސް',
    'tower': 'ބުރުޒު',
    'star': 'ތަރި',
    'moon': 'ސަނދު',
    'sun': 'އިރު',
    'judgement': 'ފަހުބަސް',
    'world': 'ދުނިޔެ',
  };
  return map[slug.toLowerCase()] ?? '';
}
